In [10]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [11]:
from sklearn.model_selection import train_test_split, GridSearchCV

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

from sklearn.linear_model import LogisticRegression

In [12]:
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [13]:
df.drop(columns=['class','who','adult_male','deck','embark_town','alive','alone'],inplace=True)
df.head()

   survived  pclass     sex   age  sibsp  parch     fare embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [25]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['survived']), df['survived'], test_size=0.2,random_state=42)
print(y_test.head())
X_train.head()

709    1
439    0
840    0
720    1
39     1
Name: survived, dtype: int64

     pclass     sex   age  sibsp  parch     fare embarked
331       1    male  45.5      0      0  28.5000        S
733       2    male  23.0      0      0  13.0000        S
382       3    male  32.0      0      0   7.9250        S
704       3    male  26.0      1      0   7.8542        S
813       3  female   6.0      4      2  31.2750        S

In [26]:
num = ['age','fare']
cat = ['sex','embarked']

# the Pipelines to deal with numerical and categorical features
setting the transformers for pre-processing

In [29]:
# --------------------------------------------------------------------------

num_trf = Pipeline(
    steps=[
        ('impute', SimpleImputer(strategy='median')),
        ('scale', StandardScaler())
    ]
)

# --------------------------------------------------------------------------

cat_trf = Pipeline(
    steps = [
        ('impute', SimpleImputer(strategy='most_frequent')),
        ('ohe',    OneHotEncoder(handle_unknown='ignore'))
    ]
)

# the pipeline used in column transformer
> i don't know why this order

In [30]:
pre_processor = ColumnTransformer(
    transformers = [
        ('num',num_trf,num),
        ('cat',cat_trf,cat)
    ]
)

# final column transformer - to - pipeline 
> for final model

In [31]:
clf = Pipeline(
    steps = [
        ('pre-processor', pre_processor),
        ('Logistic Regression', LogisticRegression())
    ]
)

In [35]:
from sklearn import set_config

set_config(display='diagram')
clf

Pipeline(steps=[('pre-processor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scale',
                                                                   StandardScaler())]),
                                                  ['age', 'fare']),
                                                 ('cat',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('ohe',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['sex', 'embarked'])])),
                ('Logistic Regression', LogisticRegression())])

In [ ]:
param_set = {
    '':'',
    '':''
}