In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

In [3]:
# %pip install kagglehub

In [4]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("rakeshrau/social-network-ads")

print("Path to dataset files:", path)

c:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Path to dataset files: C:\Users\HP\.cache\kagglehub\datasets\rakeshrau\social-network-ads\versions\1

In [5]:
df = pd.read_csv(path + "/Social_Network_Ads.csv")
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [6]:
df.drop(['User ID', 'Gender'], axis=1, inplace=True)

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.drop('Purchased', axis=1), df['Purchased'], test_size=0.2, random_state=0)

In [8]:
print(X_train.shape)
X_test.shape

(320, 2)

(80, 2)

In [9]:
X_train.head()

     Age  EstimatedSalary
336   58           144000
64    59            83000
55    24            55000
106   26            35000
300   58            38000

In [10]:
sc.fit(X_train)

print(sc.mean_)
print(sc.scale_)
print(sc.var_)

[3.8218750e+01 6.9928125e+04]
[1.02869285e+01 3.45159993e+04]
[1.05820898e+02 1.19135421e+09]

In [11]:
X_train_scaled = sc.transform(X_train)
X_test_scaled = sc.transform(X_test)

In [12]:
# X_train_scaled.describe()

# ! the error is because the sc.transform converts the DF to an ndarray

In [13]:
X_train_scaled = pd.DataFrame(X_train_scaled, columns=X_train.columns)
X_train_scaled.describe().round()

         Age  EstimatedSalary
count  320.0            320.0
mean     0.0              0.0
std      1.0              1.0
min     -2.0             -2.0
25%     -1.0             -1.0
50%     -0.0             -0.0
75%      1.0              1.0
max      2.0              2.0

In [14]:
X_test_scaled = pd.DataFrame(X_test_scaled, columns=X_test.columns)
X_test_scaled.describe().round()

        Age  EstimatedSalary
count  80.0             80.0
mean   -0.0             -0.0
std     1.0              1.0
min    -2.0             -2.0
25%    -1.0             -1.0
50%    -0.0              0.0
75%     0.0              0.0
max     2.0              2.0