In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
df = sns.load_dataset('titanic')
df.head(3)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True

In [3]:
df = df[['survived', 'pclass','sex','age','sibsp','parch','fare','embarked']]
df

     survived  pclass     sex   age  sibsp  parch     fare embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female   NaN      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
X_train,X_test, y_train, y_test = train_test_split(df.drop('survived', axis=1),df['survived'],test_size=0.2, random_state=42)

In [9]:
X_train.head(2)

     pclass   sex   age  sibsp  parch  fare embarked
331       1  male  45.5      0      0  28.5        S
733       2  male  23.0      0      0  13.0        S

In [8]:
X_test.head(2)

     pclass   sex   age  sibsp  parch     fare embarked
709       3  male   NaN      1      1  15.2458        C
439       2  male  31.0      0      0  10.5000        S

In [12]:
y_train.head()

331    0
733    0
382    0
704    0
813    0
Name: survived, dtype: int64

In [13]:
df.isnull().sum()

survived      0
pclass        0
sex           0
age         177
sibsp         0
parch         0
fare          0
embarked      2
dtype: int64

---
# Simple imputer

In [15]:
from sklearn.impute import SimpleImputer

In [16]:
si = SimpleImputer()
si_embarked = SimpleImputer(strategy='most_frequent')

In [19]:
X_train_age = si.fit_transform(X_train[['age']])
X_train_embarked = si_embarked.fit_transform(X_train[['embarked']])

In [20]:
X_test_age = si.fit_transform(X_test[['age']])
X_test_embarked = si_embarked.fit_transform(X_test[['embarked']])

---
# One Hot Encoding

In [22]:
from sklearn.preprocessing import OneHotEncoder

In [23]:
ohe_sex = OneHotEncoder(sparse=False,handle_unknown='ignore')

TypeError: OneHotEncoder.__init__() got an unexpected keyword argument 'sparse'